trigger:
  - main


pool: server

variables:
  gitHubEnterpriseUrl: https://github.enterprise/your-organization/your-repository
  nexusUrl: https://nexus.example.com/repository/your-repository
  ansiblePlaybooksPath: ./ansible

stages:
- stage: Development
  jobs:
  - job: DevelopmentDeployment
    steps:

    - task: CmdLine@2
      displayName: Run Python Unit Tests
      inputs:
        script: echo tests

    - task: CmdLine@2
      displayName: Build Task
      inputs:
        script: echo build
        

    - task: CmdLine@2
      displayName: Push Artifacts to Nexus
      inputs:
        script: echo nexus push

    - task: CmdLine@2
      displayName: Deploy to Dev
      inputs:
        script: echo ansible deploy
    
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          satyanmandavilli@outlook.com
          example@example.com
        instructions: 'Please review the changes and approve deployment to QA.'
        onTimeout: 'reject'
- stage: QA
  dependsOn: Development
  jobs:
  - job: QADeployment
    steps:
    - task: CmdLine@2
      displayName: Deploy to QA
      inputs:
        script: echo ansible deploy QA

    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          satyanmandavilli@outlook.com
          example@example.com
        instructions: 'Please review the changes and approve deployment to QA.'
        onTimeout: 'reject'

- stage: Production
  dependsOn: QA
  jobs:
  - job: ProductionDeployment
    steps:
    - task: CmdLine@2
      displayName: Deploy to PROD
      inputs:
        script: echo ansible deploy PROD
